// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDPDay9LabCF.Models;

#nullable disable

namespace PDPDay9LabCF.Migrations
{
    [DbContext(typeof(PDPDay9LabCFContext))]
    [Migration("20251017162308_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PDPDay9LabCF.Models.PDPLoai_San_Pham", b =>
                {
                    b.Property<long>("pdpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("pdpId"));

                    b.Property<string>("pdpMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("pdpTenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("pdpTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("pdpId");

                    b.HasIndex("pdpMaLoai")
                        .IsUnique();

                    b.ToTable("PDPLoai_San_Pham");
                });

            modelBuilder.Entity("PDPDay9LabCF.Models.PDPSan_Pham", b =>
                {
                    b.Property<long>("pdpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("pdpId"));

                    b.Property<decimal>("pdpDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("pdpHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("pdpLoaiSanPhamId")
                        .HasColumnType("bigint");

                    b.Property<long>("pdpLoai_San_PhampdpId")
                        .HasColumnType("bigint");

                    b.Property<string>("pdpMaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("pdpSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("pdpTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pdpId");

                    b.HasIndex("pdpLoai_San_PhampdpId");

                    b.ToTable("PDPSan_Pham");
                });

            modelBuilder.Entity("PDPDay9LabCF.Models.PDPSan_Pham", b =>
                {
                    b.HasOne("PDPDay9LabCF.Models.PDPLoai_San_Pham", "pdpLoai_San_Pham")
                        .WithMany("pdpSan_Phams")
                        .HasForeignKey("pdpLoai_San_PhampdpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pdpLoai_San_Pham");
                });

            modelBuilder.Entity("PDPDay9LabCF.Models.PDPLoai_San_Pham", b =>
                {
                    b.Navigation("pdpSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
